<div id="modal-content">
        <?php echo $block->getContent(); ?>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                modal
            ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Example Modal',
                    buttons: [{
                        text: $.mage.__(‘OK’),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };
     
                var popup = modal(options, $('#modal-content’));
                $('#modal-content’).modal('openModal');
            }  
        );
    </script>